In [40]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import OrdinalEncoder

In [41]:
df  = pd.read_csv('laptop.csv')
df = df.iloc[:,2:]
df.head()

Company   TypeName Inches                    ScreenResolution  \
0   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   
1   Apple  Ultrabook   13.3                            1440x900   
2      HP   Notebook   15.6                   Full HD 1920x1080   
3   Apple  Ultrabook   15.4  IPS Panel Retina Display 2880x1800   
4   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   

                          Cpu   Ram               Memory  \
0        Intel Core i5 2.3GHz   8GB            128GB SSD   
1        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3        Intel Core i7 2.7GHz  16GB            512GB SSD   
4        Intel Core i5 3.1GHz   8GB            256GB SSD   

                            Gpu  OpSys  Weight        Price  
0  Intel Iris Plus Graphics 640  macOS  1.37kg   71378.6832  
1        Intel HD Graphics 6000  macOS  1.34kg   47895.5232  
2         Intel HD Graphics 620  No OS  1.86kg   30636.0000  
3            AMD Radeon Pro 455  macOS  1.83kg  135195.3360  
4  Intel Iris Plus Graphics 650  macOS  1.37kg   96095.8080

In [42]:
df.columns = df.columns.str.lower()

In [43]:
df.head()

company   typename inches                    screenresolution  \
0   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   
1   Apple  Ultrabook   13.3                            1440x900   
2      HP   Notebook   15.6                   Full HD 1920x1080   
3   Apple  Ultrabook   15.4  IPS Panel Retina Display 2880x1800   
4   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   

                          cpu   ram               memory  \
0        Intel Core i5 2.3GHz   8GB            128GB SSD   
1        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3        Intel Core i7 2.7GHz  16GB            512GB SSD   
4        Intel Core i5 3.1GHz   8GB            256GB SSD   

                            gpu  opsys  weight        price  
0  Intel Iris Plus Graphics 640  macOS  1.37kg   71378.6832  
1        Intel HD Graphics 6000  macOS  1.34kg   47895.5232  
2         Intel HD Graphics 620  No OS  1.86kg   30636.0000  
3            AMD Radeon Pro 455  macOS  1.83kg  135195.3360  
4  Intel Iris Plus Graphics 650  macOS  1.37kg   96095.8080

In [44]:
df = df.dropna()
df = df.reset_index(drop=True)
df.head()

company   typename inches                    screenresolution  \
0   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   
1   Apple  Ultrabook   13.3                            1440x900   
2      HP   Notebook   15.6                   Full HD 1920x1080   
3   Apple  Ultrabook   15.4  IPS Panel Retina Display 2880x1800   
4   Apple  Ultrabook   13.3  IPS Panel Retina Display 2560x1600   

                          cpu   ram               memory  \
0        Intel Core i5 2.3GHz   8GB            128GB SSD   
1        Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2  Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3        Intel Core i7 2.7GHz  16GB            512GB SSD   
4        Intel Core i5 3.1GHz   8GB            256GB SSD   

                            gpu  opsys  weight        price  
0  Intel Iris Plus Graphics 640  macOS  1.37kg   71378.6832  
1        Intel HD Graphics 6000  macOS  1.34kg   47895.5232  
2         Intel HD Graphics 620  No OS  1.86kg   30636.0000  
3            AMD Radeon Pro 455  macOS  1.83kg  135195.3360  
4  Intel Iris Plus Graphics 650  macOS  1.37kg   96095.8080

In [45]:
df['inches'] = df['inches'].replace({'?':df['inches'].mode()[0]}).astype('float64')
df['inches'].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 31.6, 17. , 15. , 14.1,
       11.3, 10.1])

In [46]:
df['weight'] = df['weight'].str.replace('kg','')
df['weight'] = df['weight'].replace({'?':df['weight'].mode()[0]}).astype('float64')
df['weight'].unique()

array([1.370e+00, 1.340e+00, 1.860e+00, 1.830e+00, 2.100e+00, 2.040e+00,
       1.300e+00, 1.600e+00, 2.200e+00, 9.200e-01, 1.220e+00, 2.500e+00,
       1.620e+00, 1.910e+00, 2.300e+00, 1.350e+00, 1.880e+00, 1.890e+00,
       1.650e+00, 2.710e+00, 1.200e+00, 1.440e+00, 2.800e+00, 2.000e+00,
       2.650e+00, 2.770e+00, 3.200e+00, 1.490e+00, 2.400e+00, 2.130e+00,
       2.430e+00, 1.700e+00, 1.400e+00, 1.800e+00, 1.900e+00, 3.000e+00,
       1.252e+00, 2.700e+00, 2.020e+00, 1.630e+00, 1.960e+00, 1.210e+00,
       2.450e+00, 1.250e+00, 1.500e+00, 2.620e+00, 1.380e+00, 1.580e+00,
       1.850e+00, 1.230e+00, 2.160e+00, 2.360e+00, 7.200e+00, 2.050e+00,
       1.320e+00, 1.750e+00, 9.700e-01, 2.560e+00, 1.480e+00, 1.740e+00,
       1.100e+00, 1.560e+00, 2.030e+00, 1.050e+00, 5.400e+00, 4.400e+00,
       1.290e+00, 1.950e+00, 2.060e+00, 1.120e+00, 3.490e+00, 3.350e+00,
       2.230e+00, 2.900e+00, 4.420e+00, 2.690e+00, 2.370e+00, 4.700e+00,
       3.600e+00, 2.080e+00, 4.300e+00, 1.680e+00, 

In [47]:
df['ram'] = df['ram'].str.replace('GB','').astype('float64')
df['ram'].unique()

array([ 8., 16.,  4.,  2., 12., 64.,  6., 32., 24.,  1.])

In [48]:
df.isnull().any()

company             False
typename            False
inches              False
screenresolution    False
cpu                 False
ram                 False
memory              False
gpu                 False
opsys               False
weight              False
price               False
dtype: bool

In [49]:
categorical_columns = df.select_dtypes(include = 'object').columns

In [50]:
oe = OrdinalEncoder()
oe_array = oe.fit_transform(df[categorical_columns]) 
oe_df = pd.DataFrame(oe_array,columns=categorical_columns)
oe_df

company  typename  screenresolution   cpu  memory   gpu  opsys
0         1.0       4.0              23.0  65.0     4.0  58.0    8.0
1         1.0       4.0               1.0  63.0     2.0  51.0    8.0
2         7.0       3.0               8.0  74.0    16.0  53.0    4.0
3         1.0       4.0              25.0  85.0    29.0   9.0    8.0
4         1.0       4.0              23.0  67.0    16.0  59.0    8.0
...       ...       ...               ...   ...     ...   ...    ...
1268     10.0       0.0              13.0  89.0     4.0  47.0    5.0
1269     10.0       0.0              19.0  89.0    29.0  47.0    5.0
1270     10.0       3.0               0.0  34.0    35.0  40.0    5.0
1271      7.0       3.0               0.0  89.0    10.0  21.0    5.0
1272      2.0       3.0               0.0  34.0    26.0  40.0    5.0

[1273 rows x 7 columns]

In [51]:
X = pd.concat([oe_df,df.select_dtypes(include='number')],axis=1)
X = X.iloc[:,:-1]
y = df['price']
# y = np.log(df['price']+1e-8)


In [52]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X.loc[:,:] = sc.fit_transform(X)
X

company  typename  screenresolution       cpu    memory       gpu  \
0    -1.325418  1.138726          1.755790 -0.471953 -1.540969  0.148683   
1    -1.325418  1.138726         -1.046709 -0.551094 -1.789815 -0.174466   
2     0.137522  0.334288         -0.155005 -0.115820 -0.047893 -0.082138   
3    -1.325418  1.138726          2.010563  0.319454  1.569606 -2.113359   
4    -1.325418  1.138726          1.755790 -0.392813 -0.047893  0.194847   
...        ...       ...               ...       ...       ...       ...   
1268  0.868991 -2.079029          0.481927  0.477735 -1.540969 -0.359123   
1269  0.868991 -2.079029          1.246245  0.477735  1.569606 -0.359123   
1270  0.868991  0.334288         -1.174096 -1.698634  2.316144 -0.682272   
1271  0.137522  0.334288         -1.174096  0.477735 -0.794431 -1.559390   
1272 -1.081595  0.334288         -1.174096 -1.698634  1.196337 -0.682272   

         opsys    inches       ram    weight  
0     3.081637 -0.937654 -0.083184 -0.876773  
1     3.081637 -0.937654 -0.083184 -0.913940  
2    -0.786171  0.240055 -0.083184 -0.269722  
3     3.081637  0.137645  1.355090 -0.306888  
4     3.081637 -0.937654 -0.083184 -0.876773  
...        ...       ...       ...       ...  
1268  0.180781 -0.579221 -0.802321 -0.344055  
1269  0.180781 -0.937654  1.355090 -0.963495  
1270  0.180781 -0.579221 -1.161889 -0.715719  
1271  0.180781  0.240055 -0.442752  0.139109  
1272  0.180781  0.240055 -0.802321  0.151497  

[1273 rows x 10 columns]

In [53]:
y

0        71378.6832
1        47895.5232
2        30636.0000
3       135195.3360
4        96095.8080
           ...     
1268     33992.6400
1269     79866.7200
1270     12201.1200
1271     40705.9200
1272     19660.3200
Name: price, Length: 1273, dtype: float64

In [54]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [55]:
print(X_train.shape) 
print(y_train.shape) 
print(X_test.shape)
print(y_test.shape)

(1018, 10)
(1018,)
(255, 10)
(255,)


In [56]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(max_depth=5)
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()

In [57]:
from sklearn.model_selection import cross_val_score
model = cross_val_score(estimator=rfr,X=X_train,y=y_train,cv=5,scoring = 'neg_root_mean_squared_error')

In [58]:
print(-model.mean())
-model

16251.50167798932


array([15312.11400818, 14838.71464338, 16673.70372637, 14308.25778476,
       20124.71822727])

In [59]:
model = rfr.fit(X_train,y_train)
y_train_pred = model.predict(X_train) 
y_test_pred = model.predict(X_test)

In [60]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,root_mean_squared_error

In [61]:
# Calculate Metrics
# y_train = np.exp(y_train) 
# y_test = np.exp(y_test) 
# y_train_pred = np.exp(y_train_pred) 
# y_test_pred = np.exp(y_test_pred)

train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MAE: {train_mae:.2f}, Test MAE: {test_mae:.2f}")
print(f"Train R²: {train_r2:.2f}, Test R²: {test_r2:.2f}")

Train MAE: 3491.92, Test MAE: 9642.27
Train R²: 0.98, Test R²: 0.81


In [62]:
# Calculate Metrics
train_mae = mean_absolute_error(y_train, y_train_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)
train_rmse = root_mean_squared_error(y_train,y_train_pred)
test_rmse = root_mean_squared_error(y_test, y_test_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MAE: {train_mae:.2f}, Test MAE: {test_mae:.2f}")
print(f"Train RMSE: {train_rmse:.2f}, Test RMSE: {test_rmse:.2f}")

print(f"Train R²: {train_r2:.2f}, Test R²: {test_r2:.2f}")

Train MAE: 3491.92, Test MAE: 9642.27
Train RMSE: 5587.24, Test RMSE: 16533.45
Train R²: 0.98, Test R²: 0.81


In [38]:
metrics_dict = {}
my_columns = [col for col in df.columns if col!='price']
for i in my_columns:
    cols = ['ram','gpu','weight','screenresolution'] + [i] 
    cols = list(set(cols)) 
    X_temp = X[cols]
    sc = StandardScaler()
    X_temp_array = sc.fit_transform(X_temp)
    X_temp = pd.DataFrame(X_temp_array,columns = cols)
    X_train,X_test,y_train,y_test = train_test_split(X_temp,y,test_size=0.1,random_state=42)
    rfr = RandomForestRegressor()
    model = rfr.fit(X_train,y_train)
    y_train_pred = model.predict(X_train) 
    y_test_pred = model.predict(X_test)

    train_rmse = root_mean_squared_error(y_train,y_train_pred)
    test_rmse = root_mean_squared_error(y_test, y_test_pred)
    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    metrics_dict[','.join(cols)] = [train_rmse,test_rmse,train_r2,test_r2]

In [39]:
my_df = pd.DataFrame(metrics_dict).T
my_df.columns = ['Trainrmse','Testrmse','train_r2','test_r2']
my_df

Trainrmse      Testrmse  train_r2  \
weight,screenresolution,company,ram,gpu   7234.453208  17625.811701  0.961976   
weight,typename,screenresolution,ram,gpu  7285.032570  18055.700418  0.961442   
weight,gpu,screenresolution,ram,inches    7273.614775  17991.655280  0.961563   
screenresolution,weight,ram,gpu           7627.199530  18053.177269  0.957735   
weight,cpu,screenresolution,ram,gpu       6599.509301  17801.764300  0.968357   
weight,screenresolution,memory,ram,gpu    6726.658504  17988.059745  0.967126   
weight,gpu,screenresolution,ram,opsys     7310.045916  17413.183386  0.961177   

                                           test_r2  
weight,screenresolution,company,ram,gpu   0.797682  
weight,typename,screenresolution,ram,gpu  0.787692  
weight,gpu,screenresolution,ram,inches    0.789196  
screenresolution,weight,ram,gpu           0.787752  
weight,cpu,screenresolution,ram,gpu       0.793622  
weight,screenresolution,memory,ram,gpu    0.789280  
weight,gpu,screenresolution,ram,opsys     0.802534

y_test.std()

a = 12345
a_log = np.log(a+1e-8)
print(a_log)
print(np.exp(a_log))

def reverse_transform(data):
    sc_rev_array = sc.inverse_transform(data)
    sc_df = pd.DataFrame(sc_rev_array,columns = data.columns)
    oe_rev_array = oe.inverse_transform(sc_df[categorical_columns])
    oe_df = pd.DataFrame(oe_rev_array,columns = categorical_columns)
    my_df = pd.concat([oe_df,sc_df.loc[:,[col for col in sc_df.columns if col not in categorical_columns]]],axis=1)
    my_df = my_df[df.columns[:-1]]
    return my_df
reverse_transform(my_data)

my_data = X_train.iloc[10:11,:]
index= my_data.index
print(index)
my_data


reverse_transform(my_data)

result = np.exp(model.predict(my_data))
result

result = 

df.loc[index,:]

#### SIMPLE ENCODING OF CATEGORY COLUMNS

In [ ]:
# # Initializing ordinal encoder object for missing value treatment(mvt)
# oe_mvt = OrdinalEncoder()

# # Seperating objects and number columns 
# df_category = df_edit.select_dtypes(include=['object'])
# df_numerical = df_edit.select_dtypes(include= ['number'])

# # Encoding Category column
# df_category.iloc[:,:] = oe_mvt.fit_transform(df_category)
# # Encoded columns should be int
# df_category = df_category.astype('Int64')
# df_category

In [ ]:
# # Concating the category and numerical columns 
# df_edit = pd.concat([df_category,df_numerical],axis=1)
# df_edit.head()

company  typename  cpu  ...  aspect_ratio  is_touchscreen     ppi
0        1         4   65  ...          1.60               0  226.98
1        1         4   63  ...          1.60               0  127.68
2        7         3   74  ...          1.78               0  141.21
3        1         4   85  ...          1.60               0  220.53
4        1         4   67  ...          1.60               0  226.98

[5 rows x 20 columns]

In [ ]:
# Seperating target variable so that it doesn't influence the imputation
df_X = df_edit[[col for col in df_edit.columns if col!='price']]
df_y = df_edit[['price']]

# Initializing imputer object
knnimputer = KNNImputer(n_neighbors=7) 

#Fitting and transforming the data
df_imputed = pd.DataFrame(knnimputer.fit_transform(df_X),columns = df_X.columns)
df_imputed[df_category.columns] = df_imputed[df_category.columns].round().astype(int)
df_X = df_imputed.copy()
df_X.head()

company  typename  cpu  ...  aspect_ratio  is_touchscreen     ppi
0        1         4   65  ...          1.60             0.0  226.98
1        1         4   63  ...          1.60             0.0  127.68
2        7         3   74  ...          1.78             0.0  141.21
3        1         4   85  ...          1.60             0.0  220.53
4        1         4   67  ...          1.60             0.0  226.98

[5 rows x 19 columns]

In [ ]:
df_category_decoded= pd.DataFrame(oe_mvt.inverse_transform(df_X[df_category.columns]),columns = df_category.columns)
df_X = df_X[[col for col in df_numerical.columns if col!='price']]
df_X[df_category.columns] = df_category_decoded
df_X = df_X[df_category.columns.to_list()+[col for col in df_numerical.columns if col!='price']]
df_X.head()
# df_category.head()


company   typename  ... is_touchscreen     ppi
0   Apple  Ultrabook  ...            0.0  226.98
1   Apple  Ultrabook  ...            0.0  127.68
2      HP   Notebook  ...            0.0  141.21
3   Apple  Ultrabook  ...            0.0  220.53
4   Apple  Ultrabook  ...            0.0  226.98

[5 rows x 19 columns]

In [ ]:
df = pd.concat([df_X,df_y],axis = 1)
df.head()

company   typename  ...     ppi        price
0   Apple  Ultrabook  ...  226.98   71378.6832
1   Apple  Ultrabook  ...  127.68   47895.5232
2      HP   Notebook  ...  141.21   30636.0000
3   Apple  Ultrabook  ...  220.53  135195.3360
4   Apple  Ultrabook  ...  226.98   96095.8080

[5 rows x 20 columns]